# -*- coding: utf-8 -*-
"""adverrisemen_recomandation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-QMmdhZsOwBpPZH8GAFbH3zajoB1su7O
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = {
    'Clicks': [1000, 800, 1200, 1500, 2000, 1800, 1100, 1300, 1700, 1400],
    'Impressions': [50000, 60000, 55000, 70000, 80000, 75000, 52000, 58000, 68000, 60000],
    'Ad_Spend': [500, 600, 550, 700, 800, 750, 520, 580, 680, 600],
    'Ad_Response': [1, 0, 1, 1, 0, 1, 0, 1, 1, 0]  # 1 for response, 0 for no response
}

df = pd.DataFrame(data)

X = df[['Clicks', 'Impressions', 'Ad_Spend']]
y = df['Ad_Response']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

new_ad = {'Clicks': 1200, 'Impressions': 60000, 'Ad_Spend': 600}
new_ad_df = pd.DataFrame([new_ad])
prediction = model.predict(new_ad_df)
if prediction[0] == 1:
    print("Predicted Response: Yes")
else:
    print("Predicted Response: No")
print(' ')

print('Sushim Padwekar');
print('Anurag Bomenwar');
print('Vidisha Dongre');
print('Shreyash Dhawangale');
print('Pooja Zodape');